export const LOAD_PROFILE_START = "LOAD_PROFILE_START";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_PROFILE_FAILURE = "LOAD_PROFILE_FAILURE";
export const LOAD_PROFILE_NOT_FOUND = "LOAD_PROFILE_NOT_FOUND";
export const SAVE_PROFILE_START = "SAVE_PROFILE_START";
export const SAVE_PROFILE_SUCCESS = "SAVE_PROFILE_SUCCESS";
export const SAVE_PROFILE_FAILURE = "SAVE_PROFILE_FAILURE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
